import {
  Account,
  Category,
  FixedExpense,
  FinancialGoal,
  IncomeSource,
  Investment,
  UserProfile,
  Transaction,
} from '../types';

export const DEFAULT_CATEGORIES: Category[] = [
  // Necessidades (50%)
  { id: 'cat-moradia', name: 'Moradia', icon: 'Home', color: '#3B82F6', type: 'expense', budgetGroup: 'necessities' },
  { id: 'cat-contas', name: 'Contas Fixas', icon: 'Zap', color: '#6366F1', type: 'expense', budgetGroup: 'necessities' },
  { id: 'cat-alimentacao', name: 'Alimentação', icon: 'Utensils', color: '#10B981', type: 'expense', budgetGroup: 'necessities' },
  { id: 'cat-transporte', name: 'Transporte', icon: 'Car', color: '#F59E0B', type: 'expense', budgetGroup: 'necessities' },
  { id: 'cat-saude', name: 'Saúde', icon: 'HeartPulse', color: '#EC4899', type: 'expense', budgetGroup: 'necessities' },
  { id: 'cat-educacao', name: 'Educação', icon: 'GraduationCap', color: '#8B5CF6', type: 'expense', budgetGroup: 'necessities' },
  { id: 'cat-dividas', name: 'Dívidas & Financiamentos', icon: 'CreditCard', color: '#EF4444', type: 'expense', budgetGroup: 'necessities' },
  
  // Lazer e Desejos (30%)
  { id: 'cat-lazer', name: 'Lazer & Entretenimento', icon: 'Sparkles', color: '#F97316', type: 'expense', budgetGroup: 'leisure' },
  { id: 'cat-compras', name: 'Compras Pessoais', icon: 'ShoppingBag', color: '#14B8A6', type: 'expense', budgetGroup: 'leisure' },
  { id: 'cat-viagem', name: 'Viagens & Passeios', icon: 'Plane', color: '#06B6D4', type: 'expense', budgetGroup: 'leisure' },
  { id: 'cat-restaurantes', name: 'Restaurantes & Bares', icon: 'Coffee', color: '#EAB308', type: 'expense', budgetGroup: 'leisure' },
  { id: 'cat-assinaturas', name: 'Assinaturas & Streaming', icon: 'Tv', color: '#A855F7', type: 'expense', budgetGroup: 'leisure' },

  // Investimentos (20%)
  { id: 'cat-investimentos', name: 'Aportes & Investimentos', icon: 'TrendingUp', color: '#059669', type: 'expense', budgetGroup: 'investments' },
  { id: 'cat-reserva', name: 'Reserva de Emergência', icon: 'ShieldCheck', color: '#0D9488', type: 'expense', budgetGroup: 'investments' },

  // Rendas
  { id: 'cat-salario', name: 'Salário', icon: 'Briefcase', color: '#10B981', type: 'income', budgetGroup: 'necessities' },
  { id: 'cat-comissao', name: 'Comissão', icon: 'DollarSign', color: '#3B82F6', type: 'income', budgetGroup: 'necessities' },
  { id: 'cat-lucro', name: 'Lucro de Empresa', icon: 'Building', color: '#8B5CF6', type: 'income', budgetGroup: 'necessities' },
  { id: 'cat-rendimento', name: 'Rendimentos & Dividendos', icon: 'Percent', color: '#059669', type: 'income', budgetGroup: 'necessities' },
  { id: 'cat-outros-renda', name: 'Outras Entradas', icon: 'PlusCircle', color: '#6B7280', type: 'income', budgetGroup: 'necessities' },
];

export const DEFAULT_ACCOUNTS: Account[] = [
  { id: 'acc-nubank', name: 'Nubank', institution: 'Nubank', type: 'checking', balance: 0.0, color: '#820AD1' },
  { id: 'acc-inter', name: 'Banco Inter', institution: 'Banco Inter', type: 'investment', balance: 0.0, color: '#FF7A00' },
  { id: 'acc-sicredi', name: 'Sicredi', institution: 'Sicredi', type: 'checking', balance: 0.0, color: '#006633' },
  { id: 'acc-carteira', name: 'Carteira Física', institution: 'Dinheiro', type: 'wallet', balance: 0.0, color: '#4B5563' },
];

export const DEFAULT_BLANK_ACCOUNTS: Account[] = [
  { id: 'acc-nubank', name: 'Nubank', institution: 'Nubank', type: 'checking', balance: 0.0, color: '#820AD1' },
  { id: 'acc-inter', name: 'Banco Inter', institution: 'Banco Inter', type: 'investment', balance: 0.0, color: '#FF7A00' },
  { id: 'acc-sicredi', name: 'Sicredi', institution: 'Sicredi', type: 'checking', balance: 0.0, color: '#006633' },
  { id: 'acc-carteira', name: 'Carteira Física', institution: 'Dinheiro', type: 'wallet', balance: 0.0, color: '#4B5563' },
];

export function getBlankUserData(userName: string = 'Usuário', userEmail: string = '') {
  const profile: UserProfile = {
    id: 'user-local',
    name: userName,
    email: userEmail.toLowerCase(),
    emergencyGoal: 30000.0,
    monthlyInvestmentGoalPercent: 20,
    budgetRule: {
      necessitiesPercent: 50,
      leisurePercent: 30,
      investmentsPercent: 20,
    },
    hasCompletedOnboarding: true,
    createdAt: new Date().toISOString(),
  };

  return {
    profile,
    accounts: DEFAULT_BLANK_ACCOUNTS,
    categories: DEFAULT_CATEGORIES,
    transactions: [] as Transaction[],
    fixedExpenses: [] as FixedExpense[],
    incomeSources: [] as IncomeSource[],
    investments: [] as Investment[],
    goals: [] as FinancialGoal[],
  };
}

export function getInitialSeedData(userName: string = 'Usuário Demo', userEmail: string = 'demo@exemplo.com') {
  const profile: UserProfile = {
    id: 'user-default',
    name: userName,
    email: userEmail,
    emergencyGoal: 40000.0,
    monthlyInvestmentGoalPercent: 20,
    budgetRule: {
      necessitiesPercent: 50,
      leisurePercent: 30,
      investmentsPercent: 20,
    },
    hasCompletedOnboarding: true,
    createdAt: new Date().toISOString(),
  };

  const incomeSources: IncomeSource[] = [
    {
      id: 'inc-1',
      name: 'Salário',
      amount: 2500.0,
      type: 'fixed',
      receiveDay: 5,
      categoryId: 'cat-salario',
      accountId: 'acc-nubank',
      active: true,
      notes: 'Salário fixo CLT',
    },
    {
      id: 'inc-2',
      name: 'Comissão',
      amount: 2500.0,
      type: 'variable',
      receiveDay: 15,
      categoryId: 'cat-comissao',
      accountId: 'acc-nubank',
      active: true,
      notes: 'Média de R$ 2.000 a R$ 3.000',
    },
    {
      id: 'inc-3',
      name: 'Lucro da empresa',
      amount: 6000.0,
      type: 'variable',
      receiveDay: 27,
      categoryId: 'cat-lucro',
      accountId: 'acc-nubank',
      active: true,
      notes: 'Distribuição mensal de lucros PJ',
    },
  ];

  const fixedExpenses: FixedExpense[] = [
    {
      id: 'exp-1',
      name: 'Casa / Aluguel',
      amount: 1150.0,
      dueDay: 10,
      categoryId: 'cat-moradia',
      accountId: 'acc-nubank',
      recurrence: 'monthly',
      active: true,
    },
    {
      id: 'exp-2',
      name: 'Luz (Energia)',
      amount: 200.0,
      dueDay: 10,
      categoryId: 'cat-contas',
      accountId: 'acc-nubank',
      recurrence: 'monthly',
      active: true,
    },
    {
      id: 'exp-3',
      name: 'Água',
      amount: 45.0,
      dueDay: 10,
      categoryId: 'cat-contas',
      accountId: 'acc-nubank',
      recurrence: 'monthly',
      active: true,
    },
    {
      id: 'exp-4',
      name: 'Nubank (Fatura)',
      amount: 380.0,
      dueDay: 10,
      categoryId: 'cat-contas',
      accountId: 'acc-nubank',
      recurrence: 'monthly',
      active: true,
    },
    {
      id: 'exp-5',
      name: 'Empréstimo Sicredi',
      amount: 900.0,
      dueDay: 15,
      categoryId: 'cat-dividas',
      accountId: 'acc-sicredi',
      recurrence: 'monthly',
      active: true,
      isDebt: true,
      totalInstallments: 36,
      currentInstallment: 12,
    },
    {
      id: 'exp-6',
      name: 'Cartão Havan',
      amount: 464.0,
      dueDay: 10,
      categoryId: 'cat-compras',
      accountId: 'acc-nubank',
      recurrence: 'monthly',
      active: true,
    },
    {
      id: 'exp-7',
      name: 'Financiamento Carro',
      amount: 1790.0,
      dueDay: 27,
      categoryId: 'cat-transporte',
      accountId: 'acc-nubank',
      recurrence: 'monthly',
      active: true,
      isDebt: true,
      totalInstallments: 48,
      currentInstallment: 24,
    },
    {
      id: 'exp-8',
      name: 'Crédito pessoal',
      amount: 1300.0,
      dueDay: 20,
      categoryId: 'cat-dividas',
      accountId: 'acc-nubank',
      recurrence: 'monthly',
      active: true,
      isDebt: true,
      totalInstallments: 20,
      currentInstallment: 19, // 19 de 20 (penúltima / última parcela a ser quitada este mês)
      notes: 'Última parcela este mês! Ao quitar, libera R$ 1.300/mês no orçamento.',
    },
  ];

  const investments: Investment[] = [
    {
      id: 'inv-1',
      name: 'CDB 100% CDI Liquidez Diária',
      type: 'CDB',
      institution: 'Banco Inter',
      investedAmount: 17500.0,
      currentBalance: 18430.0,
      startDate: '2025-06-10',
      profitabilityRate: '100% CDI',
      liquidity: 'daily',
      isEmergencyReserve: true,
      cdiPercentage: 100,
      notes: 'Principal fundo da reserva de emergência',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'inv-2',
      name: 'Tesouro Selic 2029',
      type: 'Tesouro Direto',
      institution: 'NuInvest / Nubank',
      investedAmount: 2000.0,
      currentBalance: 2150.0,
      startDate: '2025-09-15',
      profitabilityRate: 'Selic + 0.15%',
      liquidity: 'd+1',
      isEmergencyReserve: false,
      notes: 'Aporte de médio prazo',
      updatedAt: new Date().toISOString(),
    },
  ];

  const goals: FinancialGoal[] = [
    {
      id: 'goal-1',
      name: 'Reserva de Emergência Ideal',
      targetAmount: 40000.0,
      currentAmount: 18430.0,
      deadline: '2027-06-30',
      category: 'Segurança',
      description: 'Proteger 6 a 8 meses do custo essencial de vida',
      color: '#059669',
      icon: 'ShieldCheck',
    },
    {
      id: 'goal-2',
      name: 'Viagem de Férias',
      targetAmount: 8000.0,
      currentAmount: 3200.0,
      deadline: '2027-01-15',
      category: 'Lazer',
      description: 'Viagem com a família no início do ano',
      color: '#06B6D4',
      icon: 'Plane',
    },
    {
      id: 'goal-3',
      name: 'Troca de Carro / Quitação',
      targetAmount: 20000.0,
      currentAmount: 4500.0,
      deadline: '2027-12-31',
      category: 'Bens',
      description: 'Amortização ou entrada para novo veículo',
      color: '#F59E0B',
      icon: 'Car',
    },
    {
      id: 'goal-4',
      name: 'Novo Computador / Setup',
      targetAmount: 10000.0,
      currentAmount: 2800.0,
      deadline: '2026-11-30',
      category: 'Trabalho',
      description: 'Upgrade do equipamento de trabalho',
      color: '#8B5CF6',
      icon: 'Laptop',
    },
  ];

  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');

  const transactions: Transaction[] = [
    {
      id: 'tx-1',
      type: 'income',
      description: 'Salário Mensal',
      amount: 2500.0,
      date: `${year}-${month}-05`,
      categoryId: 'cat-salario',
      accountId: 'acc-nubank',
      recurrence: 'monthly',
      status: 'paid',
      createdAt: `${year}-${month}-05T08:00:00Z`,
    },
    {
      id: 'tx-2',
      type: 'income',
      description: 'Comissão de Vendas',
      amount: 2500.0,
      date: `${year}-${month}-15`,
      categoryId: 'cat-comissao',
      accountId: 'acc-nubank',
      recurrence: 'monthly',
      status: 'paid',
      createdAt: `${year}-${month}-15T10:00:00Z`,
    },
    {
      id: 'tx-3',
      type: 'income',
      description: 'Lucro da Empresa (PJ)',
      amount: 6000.0,
      date: `${year}-${month}-27`,
      categoryId: 'cat-lucro',
      accountId: 'acc-nubank',
      recurrence: 'monthly',
      status: 'paid',
      createdAt: `${year}-${month}-27T14:00:00Z`,
    },
    {
      id: 'tx-4',
      type: 'expense',
      description: 'Aluguel Casa',
      amount: 1150.0,
      date: `${year}-${month}-10`,
      categoryId: 'cat-moradia',
      accountId: 'acc-nubank',
      recurrence: 'monthly',
      status: 'paid',
      createdAt: `${year}-${month}-10T09:00:00Z`,
    },
    {
      id: 'tx-5',
      type: 'expense',
      description: 'Conta de Energia (Luz)',
      amount: 200.0,
      date: `${year}-${month}-10`,
      categoryId: 'cat-contas',
      accountId: 'acc-nubank',
      recurrence: 'monthly',
      status: 'paid',
      createdAt: `${year}-${month}-10T09:30:00Z`,
    },
    {
      id: 'tx-6',
      type: 'expense',
      description: 'Conta de Água',
      amount: 45.0,
      date: `${year}-${month}-10`,
      categoryId: 'cat-contas',
      accountId: 'acc-nubank',
      recurrence: 'monthly',
      status: 'paid',
      createdAt: `${year}-${month}-10T09:35:00Z`,
    },
    {
      id: 'tx-7',
      type: 'expense',
      description: 'Fatura Nubank',
      amount: 380.0,
      date: `${year}-${month}-10`,
      categoryId: 'cat-contas',
      accountId: 'acc-nubank',
      recurrence: 'monthly',
      status: 'paid',
      createdAt: `${year}-${month}-10T10:00:00Z`,
    },
    {
      id: 'tx-8',
      type: 'expense',
      description: 'Empréstimo Sicredi (Parc 12/36)',
      amount: 900.0,
      date: `${year}-${month}-15`,
      categoryId: 'cat-dividas',
      accountId: 'acc-sicredi',
      recurrence: 'monthly',
      status: 'paid',
      createdAt: `${year}-${month}-15T11:00:00Z`,
    },
    {
      id: 'tx-9',
      type: 'expense',
      description: 'Cartão Havan',
      amount: 464.0,
      date: `${year}-${month}-10`,
      categoryId: 'cat-compras',
      accountId: 'acc-nubank',
      recurrence: 'monthly',
      status: 'paid',
      createdAt: `${year}-${month}-10T11:30:00Z`,
    },
    {
      id: 'tx-10',
      type: 'expense',
      description: 'Financiamento Carro (Parc 24/48)',
      amount: 1790.0,
      date: `${year}-${month}-27`,
      categoryId: 'cat-transporte',
      accountId: 'acc-nubank',
      recurrence: 'monthly',
      status: 'paid',
      createdAt: `${year}-${month}-27T16:00:00Z`,
    },
    {
      id: 'tx-11',
      type: 'expense',
      description: 'Crédito Pessoal (Parc 19/20 - Penúltima)',
      amount: 1300.0,
      date: `${year}-${month}-20`,
      categoryId: 'cat-dividas',
      accountId: 'acc-nubank',
      recurrence: 'monthly',
      status: 'paid',
      createdAt: `${year}-${month}-20T12:00:00Z`,
    },
    {
      id: 'tx-12',
      type: 'investment',
      description: 'Aporte CDB 100% CDI',
      amount: 2000.0,
      date: `${year}-${month}-28`,
      categoryId: 'cat-reserva',
      accountId: 'acc-inter',
      recurrence: 'monthly',
      status: 'paid',
      investmentId: 'inv-1',
      createdAt: `${year}-${month}-28T17:00:00Z`,
    },
    {
      id: 'tx-13',
      type: 'expense',
      description: 'Jantar Restaurante Fim de Semana',
      amount: 280.0,
      date: `${year}-${month}-12`,
      categoryId: 'cat-restaurantes',
      accountId: 'acc-nubank',
      recurrence: 'single',
      status: 'paid',
      createdAt: `${year}-${month}-12T21:00:00Z`,
    },
    {
      id: 'tx-14',
      type: 'expense',
      description: 'Cinema & Lanches',
      amount: 170.0,
      date: `${year}-${month}-18`,
      categoryId: 'cat-lazer',
      accountId: 'acc-nubank',
      recurrence: 'single',
      status: 'paid',
      createdAt: `${year}-${month}-18T19:30:00Z`,
    },
  ];

  return {
    profile,
    incomeSources,
    fixedExpenses,
    investments,
    goals,
    transactions,
    accounts: DEFAULT_ACCOUNTS,
    categories: DEFAULT_CATEGORIES,
  };
}
